apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: "88.2.0"
      helm:
        releaseName: kube-prometheus-stack
        valueFiles:
          - $values/prometheus/values.yaml
    - repoURL: https://github.com/delgadm/argocd.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
