apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: monitoring-gateway
  namespace: monitoring
spec:
  gatewayClassName: traefik
  listeners:
    - name: grafana
      hostname: grafana.local
      port: 8000
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
    - name: prometheus
      hostname: prometheus.local
      port: 8000
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
    - name: loki
      hostname: loki.local
      port: 8000
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
